FROM node:18-alpine AS base
WORKDIR /usr/app

FROM base AS installer

RUN echo '{\
  "name": "hardhat-project",\
  "devDependencies": {\
     "@nomicfoundation/hardhat-toolbox": "^4.0.0",\
     "hardhat": "^2.20.1"\
  }\
}' > package.json

RUN echo 'require("@nomicfoundation/hardhat-toolbox");\
module.exports = {\
  solidity: "0.8.24",\
};' > hardhat.config.js

RUN npm install

FROM base as release

LABEL org.opencontainers.image.source=https://github.com/owneraio/nodejs_ledger_adapter_skeleton

COPY --from=installer /usr/app ./

CMD [ "npx", "hardhat", "node" ]
