FROM node:18-alpine AS base
WORKDIR /usr/app

FROM base AS installer

RUN cat <<EOF > package.json 
{
  "name": "hardhat-project",
  "devDependencies": {
     "@nomicfoundation/hardhat-toolbox": "^4.0.0",
     "hardhat": "^2.20.1"
  }
}
EOF

RUN cat <<EOF > hardhat.config.js
require("@nomicfoundation/hardhat-toolbox");
module.exports = {
  solidity: "0.8.24",
  networks: {
    hardhat: {
      accounts: [
        {
          privateKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
          balance: "1000000000000000000000"
        },
        {
          privateKey: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
          balance: "1000000000000000000000"
        },
        {
          privateKey: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
          balance: "1000000000000000000000"
        }
      ]
    }
  }
};
EOF

RUN npm install

FROM base as release

LABEL org.opencontainers.image.source=https://github.com/owneraio/hardhat

COPY --from=installer /usr/app ./

CMD [ "npx", "hardhat", "node" ]
