name: Publish npm package

on:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./finp2p-contracts
    outputs:
      version: ${{ steps.get_package_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Branch name
        id: get_branch
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}
          echo ${{github.event_name}}
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
                 echo in pull request
                 branch=${GITHUB_HEAD_REF}
               else
                 echo in push
                 branch=${GITHUB_REF:11}
          fi;
          echo $branch
          branch=$(echo $branch | sed 's/[/_*+#%&$@]/-/g' )
          echo $branch
          echo ::set-output name=branch::$branch

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Yarn
        run: npm install -g yarn

      - name: Generate and build models
        run: |
          npm run compile
          npm run build

      - name: npm registry setup
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'

#      - name: Publish to public NPM repository
#        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
#        run: yarn publish --access=public
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: github npm registry setup
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@owneraio'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Version
        id: get_package_version
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            yarn --no-git-tag-version version --prerelease --preid ${{ steps.get_branch.outputs.branch }}-$(date +%s)
          fi;
          PACKAGE_VERSION=$(cat package.json|grep version|head -1|awk -F: '{ print $2 }'|sed 's/[", ]//g')
          echo $PACKAGE_VERSION
          echo ::set-output name=version::$PACKAGE_VERSION

      - name: Publish
        run: |
          yarn publish
